### ISSUE TITLE
Change time

### ISSUE THREAD

**Issue by Ultrunz** [TanguyOrtegat/esx_jb_realtimejailer#2]
Any way to change from hours to minutes?

**Comment by TanguyOrtegat** [comment]
TriggerServerEvent('esx_jb_jailer:PutInJail', playerid, data3.current.value, tonumber(jailtime)*60)

instead of 
TriggerServerEvent('esx_jb_jailer:PutInJail', playerid, data3.current.value, tonumber(jailtime)*60*60)

please try yourself and think how the script is made. i am not a bot that answers all of questions that you could find out by yourself
